// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKwJwaDMEYpQgn_k9tu_9-POxuyZWO8w',
    appId: '1:127826810927:web:308143a962d1c478fd4eda',
    messagingSenderId: '127826810927',
    projectId: 'gdsctask-321c2',
    authDomain: 'gdsctask-321c2.firebaseapp.com',
    storageBucket: 'gdsctask-321c2.appspot.com',
    measurementId: 'G-ZQ22J4JPDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEMDhX4T2mPrCdq-RXFXA8_sfpmWikZBc',
    appId: '1:127826810927:android:63383851c0f74f9efd4eda',
    messagingSenderId: '127826810927',
    projectId: 'gdsctask-321c2',
    storageBucket: 'gdsctask-321c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqggVKrF4-rPTu2LqrbPIsBgxlRtsVstc',
    appId: '1:127826810927:ios:c35cafd1117cff7ffd4eda',
    messagingSenderId: '127826810927',
    projectId: 'gdsctask-321c2',
    storageBucket: 'gdsctask-321c2.appspot.com',
    iosBundleId: 'com.arush.gdscTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqggVKrF4-rPTu2LqrbPIsBgxlRtsVstc',
    appId: '1:127826810927:ios:bc37e5ea14f753bdfd4eda',
    messagingSenderId: '127826810927',
    projectId: 'gdsctask-321c2',
    storageBucket: 'gdsctask-321c2.appspot.com',
    iosBundleId: 'com.arush.gdscTask.RunnerTests',
  );
}
